name: music_app
description: A new Flutter project.
version: 1.0.1+2

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  fpdart: ^0.4.0
  get_it: ^7.2.0
  go_router: ^6.0.0
  flutter_riverpod: ^2.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/