name: music_app
description: A new Flutter project.
version: 1.0.1+2

environment:
  sdk: ">=3.0.0 <3.1.0"
dependencies:
  bloc: ^8.0.3
  connectivity: ^3.0.6
  connectivity_plus: ^4.0.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  fpdart: ^0.6.0
  get_it: ^7.6.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/