name: music_app
description: A new Flutter project.
version: 1.0.1+2

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  bloc: ^8.0.3
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/